# Form implementation generated from reading ui file 'UI/AddEditCoffeeForm.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AddEditCoffeeForm(object):
    def setupUi(self, AddEditCoffeeForm):
        AddEditCoffeeForm.setObjectName("AddEditCoffeeForm")
        AddEditCoffeeForm.resize(400, 330)
        self.centralwidget = QtWidgets.QWidget(parent=AddEditCoffeeForm)
        self.centralwidget.setObjectName("centralwidget")
        self.nameEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.nameEdit.setGeometry(QtCore.QRect(180, 20, 200, 22))
        self.nameEdit.setObjectName("nameEdit")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 150, 22))
        self.label.setObjectName("label")
        self.roastEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.roastEdit.setGeometry(QtCore.QRect(180, 60, 200, 22))
        self.roastEdit.setObjectName("roastEdit")
        self.label1 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label1.setGeometry(QtCore.QRect(20, 60, 150, 22))
        self.label1.setObjectName("label1")
        self.formEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.formEdit.setGeometry(QtCore.QRect(180, 100, 200, 22))
        self.formEdit.setObjectName("formEdit")
        self.label2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label2.setGeometry(QtCore.QRect(20, 100, 150, 22))
        self.label2.setObjectName("label2")
        self.tasteEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.tasteEdit.setGeometry(QtCore.QRect(180, 140, 200, 22))
        self.tasteEdit.setObjectName("tasteEdit")
        self.label3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label3.setGeometry(QtCore.QRect(20, 140, 150, 22))
        self.label3.setObjectName("label3")
        self.priceEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.priceEdit.setGeometry(QtCore.QRect(180, 180, 200, 22))
        self.priceEdit.setObjectName("priceEdit")
        self.label4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label4.setGeometry(QtCore.QRect(20, 180, 150, 22))
        self.label4.setObjectName("label4")
        self.packageEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.packageEdit.setGeometry(QtCore.QRect(180, 220, 200, 22))
        self.packageEdit.setObjectName("packageEdit")
        self.label5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label5.setGeometry(QtCore.QRect(20, 220, 150, 22))
        self.label5.setObjectName("label5")
        self.saveButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.saveButton.setGeometry(QtCore.QRect(140, 270, 120, 30))
        self.saveButton.setObjectName("saveButton")
        AddEditCoffeeForm.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=AddEditCoffeeForm)
        self.menubar.setObjectName("menubar")
        AddEditCoffeeForm.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=AddEditCoffeeForm)
        self.statusbar.setObjectName("statusbar")
        AddEditCoffeeForm.setStatusBar(self.statusbar)

        self.retranslateUi(AddEditCoffeeForm)
        QtCore.QMetaObject.connectSlotsByName(AddEditCoffeeForm)

    def retranslateUi(self, AddEditCoffeeForm):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("AddEditCoffeeForm", "Название сорта"))
        self.label1.setText(_translate("AddEditCoffeeForm", "Степень обжарки"))
        self.label2.setText(_translate("AddEditCoffeeForm", "Форма"))
        self.label3.setText(_translate("AddEditCoffeeForm", "Описание вкуса"))
        self.label4.setText(_translate("AddEditCoffeeForm", "Цена"))
        self.label5.setText(_translate("AddEditCoffeeForm", "Объём упаковки"))
        self.saveButton.setText(_translate("AddEditCoffeeForm", "Сохранить"))
